- CHANGELOG.md
- wildfly-README.md
- wildfly/src/main/java/org/wildfly/extras/sunstone/api/wildfly/WildFlyNode.java
- wildfly/src/main/java/org/wildfly/extras/sunstone/api/wildfly/WildFlyNodeConfig.java
>  #4: add WildFly boot timeout property

- core/src/main/java/org/wildfly/extras/sunstone/api/impl/AbstractJCloudsCloudProvider.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/AbstractJCloudsNode.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/azure/AzureNode.java
> Improve Azure logging to include node name

- CHANGELOG.md
- arquillian/src/main/java/org/wildfly/extras/sunstone/arquillian/ArquillianConfig.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/Config.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/SshUtils.java
> Resolves #33 - fix low level issues reported by coverity static analysis

- CHANGELOG.md
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/FilesUtils.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/ObjectProperties.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/azure/AzureNode.java
> Issue #3 - protect access to temporary files

- core/src/test/java/org/wildfly/extras/sunstone/tests/AbstractCloudProviderTest.java
> Issue #2 - use only async node creation in AbstractCloudProviderTest to speed up the tests

- CHANGELOG.md
- core/src/main/java/org/wildfly/extras/sunstone/api/process/ExecBuilder.java
- core/src/test/java/org/wildfly/extras/sunstone/tests/AbstractCloudProviderTest.java
- core/src/test/java/org/wildfly/extras/sunstone/tests/ec2/EC2Test.java
> Fixes #22 - ExecBuilder.asDaemon didn't work in some cases

- CHANGELOG.md
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/AbstractJCloudsCloudProvider.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/AbstractJCloudsNode.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/Config.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/ObjectProperties.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/docker/DockerNode.java
- core/src/test/java/org/wildfly/extras/sunstone/api/impl/docker/DockerNodeTest.java
- docker-README.md
Fixes #45 
The first commit fixes overriding `"template"` property in `ObjectProperties`. The second introduces the new functionality.
> Added support for Docker volume bindings

- core/src/main/java/org/wildfly/extras/sunstone/api/impl/Config.java
All info should be in `ec2-README.md`.
> Removed superfluous comments from Config, EC2 related

- CHANGELOG.md
- arquillian-README.md
- arquillian/pom.xml
- pom.xml
- wildfly-README.md
- wildfly/pom.xml
> Fixes #51 - dependency management clean-up

- CHANGELOG.md
- README.md
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/AbstractJCloudsCloudProvider.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/AbstractJCloudsNode.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/Config.java
- core/src/main/java/org/wildfly/extras/sunstone/api/process/ExecBuilder.java
- core/src/test/java/org/wildfly/extras/sunstone/api/impl/docker/DockerBootScriptTest.java
- core/src/test/java/org/wildfly/extras/sunstone/api/impl/docker/DockerBootScriptTest.properties
> Fixes #56 - configurable sudo command and fine grained bootScript config

- arquillian-README.md
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/DynamicSshClientModule.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/ObjectProperties.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/azure/AzureCloudProvider.java
- core/src/test/java/org/wildfly/extras/sunstone/api/impl/ObjectPropertiesTest.java
@mjurc fixing a few issues related to properties, this is very loosely related to the "Variable number of nodes with the same configuration" task for the clustering test suite.
@simkam and @kwart may also be interested.
> Fixed #67 old properties are now deprecated

- CHANGELOG.md
- README.md
- core/src/main/java/org/wildfly/extras/sunstone/api/CloudProperties.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/Config.java
- core/src/test/java/org/wildfly/extras/sunstone/api/CloudPropertiesTest-conflict.properties
- core/src/test/java/org/wildfly/extras/sunstone/api/CloudPropertiesTest.java
- core/src/test/java/org/wildfly/extras/sunstone/api/CloudPropertiesTest.properties
Also added a forgotten CHANGELOG and README entry for #67 .
>  Implemented #69 reverse templates with templateTo 

- core/src/main/java/org/wildfly/extras/sunstone/api/impl/JCloudsSshClient.java
- core/src/main/java/org/wildfly/extras/sunstone/api/process/ExecBuilder.java
- core/src/main/java/org/wildfly/extras/sunstone/api/ssh/SshClient.java
added method for executing ssh command on remote note with a specified timeout
> added exec with timeout to ExecBuilder

- CHANGELOG.md
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/AbstractJCloudsCloudProvider.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/openstack/OpenstackNode.java
- wildfly/src/main/java/org/wildfly/extras/sunstone/api/wildfly/WildFlyNode.java
Fixes for OpenStack with routable private addresses (i.e. no floating IPs are assigned to VMs)
> Fixes for OpenStack with routable private addresses

- azure-arm-README.md
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/Config.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/azurearm/AzureArmCloudProvider.java
- core/src/main/java/org/wildfly/extras/sunstone/api/impl/azurearm/AzureArmNode.java
- core/src/test/java/org/wildfly/extras/sunstone/tests/azurearm/AzureArmTest.properties
- pom.xml
Adds the location property for the Azure ARM  - fixes the node initialization for Azure ARM provider.
> fix for Azure-ARM installation

- arquillian/pom.xml
- core/pom.xml
- pom.xml
- wildfly/pom.xml
> [#105] move dependencies from root to submodules

- core/src/main/java/org/wildfly/extras/sunstone/api/impl/ObjectType.java
- junit5/pom.xml
- junit5/src/main/java/sunstone/api/Parameter.java
- junit5/src/main/java/sunstone/api/WithAzureArmTemplate.java
- junit5/src/main/java/sunstone/api/WithAzureArmTemplateRepetable.java
- junit5/src/main/java/sunstone/core/AzureArmTemplateCloudDeploymentManager.java
- junit5/src/main/java/sunstone/core/AzureUtils.java
- junit5/src/main/java/sunstone/core/CloudDeploymentRegistry.java
- junit5/src/main/java/sunstone/core/JUnit5Config.java
- junit5/src/main/java/sunstone/core/SunstoneCloudDeploy.java
- junit5/src/main/java/sunstone/core/SunstoneExtension.java
- junit5/src/main/java/sunstone/core/SunstoneJUnit5Logger.java
- junit5/src/main/java/sunstone/core/SunstoneStore.java
- junit5/src/main/java/sunstone/core/TemplateCloudDeploymentManager.java
- junit5/src/main/java/sunstone/core/TimeoutUtil.java
- pom.xml
> Add JUnit5 module supporting Azure ARM templates deployment

- junit5/pom.xml
- junit5/src/main/java/sunstone/api/WithAwsCfTemplate.java
- junit5/src/main/java/sunstone/api/WithAwsCfTemplateRepetable.java
- junit5/src/main/java/sunstone/core/AwsCloudFormationCloudDeploymentManager.java
- junit5/src/main/java/sunstone/core/AwsUtils.java
- junit5/src/main/java/sunstone/core/JUnit5Config.java
- junit5/src/main/java/sunstone/core/SunstoneCloudDeploy.java
- junit5/src/main/java/sunstone/core/SunstoneExtension.java
- junit5/src/main/java/sunstone/core/SunstoneStore.java
Support for AWS CloudFormation teplates
Minor changes:
- Azure ARM template annotation JavaDoc enhancement
- Some checks for Azure properties added.
Fixes #109
> Add support for AWS CloudFormation templates

- clouds/clouds-aws/src/main/java/aws/core/AwsArchiveDeployer.java
- clouds/clouds-aws/src/main/java/aws/core/AwsArchiveDeployerProvider.java
- clouds/clouds-aws/src/main/java/aws/core/AwsIdentifiableSunstoneResource.java
- clouds/clouds-aws/src/main/java/aws/core/AwsIdentifiableSunstoneResourceUtils.java
- clouds/clouds-aws/src/main/java/aws/core/AwsSunstoneResourceInjector.java
- clouds/clouds-aws/src/main/java/aws/core/identification/AwsArchiveDeploymentAnnotation.java
- clouds/clouds-aws/src/main/java/aws/core/identification/AwsEc2Instance.java
- clouds/clouds-aws/src/main/resources/META-INF/services/sunstone.core.spi.SunstoneArchiveDeployerProvider
- clouds/clouds-aws/src/test/java/aws/cloudformation/archiveDeploy/ec2/Ec2DeploySuiteTests.java
- clouds/clouds-aws/src/test/java/aws/cloudformation/archiveDeploy/ec2/suitetests/AwsEc2DeployFirstTest.java
- clouds/clouds-aws/src/test/java/aws/cloudformation/archiveDeploy/ec2/suitetests/AwsEc2UndeployedSecondTest.java
> Add support for AWS archive deployment

- AWS-README.md
- Azure-README.md
- README.md
> Readme for native cloud functionality

- core/src/test/java/sunstone/core/cloudDeploy/annotations/CloudDeployAnnotation.java
- core/src/test/java/sunstone/core/cloudDeploy/annotations/TransitiveCloudDeployAnnotation.java
- pom.xml
> Fix annotations on cloud deploy test annotations

- core/src/main/java/sunstone/api/AbstractSetupTask.java
- core/src/main/java/sunstone/core/SunstoneExtension.java
- core/src/test/java/sunstone/core/di/StaticDITask.java
- core/src/test/java/sunstone/core/setup/SetupSuite.java
- core/src/test/java/sunstone/core/setup/suitetests/RegularClassTask.java
- core/src/test/java/sunstone/core/setup/suitetests/SetupFirstTest.java
- core/src/test/java/sunstone/core/setup/suitetests/SetupTeardownSecondTest.java
> Change cleanup -> teardown

- AWS-README.md
- Azure-README.md
- aws/pom.xml
- aws/src/main/java/sunstone/aws/api/AwsEc2Instance.java
- aws/src/main/java/sunstone/aws/impl/AwsIdentifiableSunstoneResourceUtils.java
- aws/src/test/java/aws/cloudformation/AwsTestConstants.java
- aws/src/test/java/aws/cloudformation/di/SunstoneResourceAwsSuiteTests.java
- aws/src/test/java/aws/cloudformation/di/suitetests/AwsHostnameTests.java
- aws/src/test/java/aws/cloudformation/di/suitetests/AwsStandaloneManagementClientTests.java
- azure/pom.xml
- azure/src/main/java/sunstone/azure/api/AzureVirtualMachine.java
- azure/src/main/java/sunstone/azure/impl/AzureIdentifiableSunstoneResourceUtils.java
- azure/src/test/java/sunstone/azure/armTemplates/AzureTestConstants.java
- azure/src/test/java/sunstone/azure/armTemplates/di/SunstoneResourceAzSuiteTests.java
- azure/src/test/java/sunstone/azure/armTemplates/di/suitetests/AzHostnameTests.java
- azure/src/test/java/sunstone/azure/armTemplates/di/suitetests/AzStandaloneManagementClientTests.java
- core/src/main/java/sunstone/api/OperatingMode.java
> Remove EAP references unless EAP is directly used.

- aws/src/main/java/sunstone/aws/impl/AwsArchiveDeployer.java
- aws/src/main/java/sunstone/aws/impl/AwsIdentifiableSunstoneResource.java
- aws/src/main/java/sunstone/aws/impl/AwsSunstoneDeployer.java
- aws/src/main/java/sunstone/aws/impl/AwsSunstoneResourceInjector.java
- aws/src/main/java/sunstone/aws/impl/AwsSunstoneStore.java
- azure/src/main/java/sunstone/azure/impl/AzureArchiveDeployer.java
- azure/src/main/java/sunstone/azure/impl/AzureIdentifiableSunstoneResource.java
- azure/src/main/java/sunstone/azure/impl/AzureSunstoneDeployer.java
- core/pom.xml
- core/src/main/java/sunstone/core/AbstractSunstoneCloudDeployer.java
- core/src/main/java/sunstone/core/CreaperUtils.java
- core/src/main/java/sunstone/core/SunstoneConfig.java
- core/src/main/java/sunstone/core/SunstoneExtension.java
- core/src/test/java/sunstone/core/archiveDeploy/AbstractArchiveDeployTest.java
- core/src/test/java/sunstone/core/archiveDeploy/ArchiveDeployTest.java
- pom.xml
Fixes #163 
- downgrade SR Config to 2.x (3.x is compiled with jdk 11) + javax.annotation dependency
- remove jdk11 new stuff: var, String#isBlank(), InputStream#nullInputStream() , ...
> [#163] JDK8 comatibility

- AWS-README.md
- aws/src/main/java/sunstone/aws/impl/AwsIdentifiableSunstoneResourceUtils.java
- aws/src/test/java/aws/cloudformation/AwsTestConstants.java
- aws/src/test/java/aws/cloudformation/archiveDeploy/ec2Domain/DomainEc2DeploySuiteTests.java
- aws/src/test/java/aws/cloudformation/archiveDeploy/ec2Domain/suitetests/AwsDomainEc2DeployFirstTest.java
- aws/src/test/java/aws/cloudformation/archiveDeploy/ec2Domain/suitetests/AwsDomainEc2UndeployedSecondTest.java
- aws/src/test/java/aws/cloudformation/di/suitetests/AwsDomainManagementClientTests.java
- aws/src/test/resources/sunstone.properties
- aws/src/test/resources/sunstone/aws/cloudformation/eapDomain.yaml
- core/src/main/java/sunstone/core/ConfigProperties.java
- core/src/main/java/sunstone/core/CreaperUtils.java
- core/src/main/java/sunstone/core/SunstoneExtension.java
> [#133] Add AWS domain mode support

- azure/src/test/resources/sunstone/azure/armTemplates/eap.json
> Adding missing EAP template

- aws/src/main/java/sunstone/aws/impl/AwsSunstoneDeployer.java
- aws/src/main/java/sunstone/aws/impl/AwsSunstoneDeployerProvider.java
- aws/src/test/java/aws/cloudformation/SingleTransitiveAwsCfTemplateTest.java
- azure/src/main/java/sunstone/azure/impl/AzureSunstoneDeployer.java
- azure/src/main/java/sunstone/azure/impl/AzureSunstoneDeployerProvider.java
- azure/src/test/java/sunstone/azure/armTemplates/SingleTransitiveAzArmTemplateTest.java
- core/src/main/java/sunstone/core/AnnotationUtils.java
- core/src/main/java/sunstone/core/SunstoneExtension.java
- core/src/main/java/sunstone/core/api/SunstoneCloudDeployer.java
- core/src/test/java/sunstone/core/cloudDeploy/TestSunstoneDeployer.java
> [#166][#165]Transitive cloud annotation support

- azure/pom.xml
> [#191] fix azure module dependencies

- aws/src/main/java/sunstone/aws/annotation/AwsAutoResolve.java
- aws/src/main/java/sunstone/aws/annotation/AwsEc2Instance.java
- aws/src/main/java/sunstone/aws/annotation/WithAwsCfTemplate.java
- aws/src/main/java/sunstone/aws/impl/AwsIdentifiableSunstoneResource.java
- aws/src/main/java/sunstone/aws/impl/AwsSunstoneDeployer.java
- aws/src/main/java/sunstone/aws/impl/AwsSunstoneResourceInjector.java
- azure/src/main/java/sunstone/azure/annotation/AzureVirtualMachine.java
- azure/src/main/java/sunstone/azure/annotation/AzureWebApplication.java
- azure/src/main/java/sunstone/azure/annotation/WithAzureArmTemplate.java
- azure/src/main/java/sunstone/azure/impl/AzureIdentifiableSunstoneResource.java
- azure/src/main/java/sunstone/azure/impl/AzureSunstoneDeployer.java
> [#174] stop supporting empty parameters in annotations

- core-wildfly/pom.xml
- pom.xml
> [#155] Update to creaper 2.0.2 & WildFly 26

- azure/pom.xml
- azure/src/main/java/sunstone/azure/annotation/AzurePgSqlServer.java
- azure/src/main/java/sunstone/azure/impl/AzureIdentifiableSunstoneResource.java
- azure/src/main/java/sunstone/azure/impl/AzureIdentifiableSunstoneResourceUtils.java
- azure/src/main/java/sunstone/azure/impl/AzureSunstoneResourceInjector.java
- azure/src/main/java/sunstone/azure/impl/AzureSunstoneStore.java
- azure/src/main/java/sunstone/azure/impl/AzureUtils.java
- azure/src/test/java/sunstone/azure/armTemplates/di/AzPgSqlTests.java
- azure/src/test/resources/sunstone/azure/armTemplates/posgresql.json
- pom.xml
> [#175] Add support for Azure PostgreSQL server

- aws/src/main/java/sunstone/aws/impl/AwsSunstoneDeployer.java
- azure/src/main/java/sunstone/azure/impl/AzureSunstoneDeployer.java
- core/src/main/java/sunstone/core/AbstractSunstoneCloudDeployer.java
- core/src/main/java/sunstone/core/SunstoneConfig.java
- core/src/main/java/sunstone/core/SunstoneExtension.java
> [#208] Allow config properties in template definitions & allow empty parameters

- Azure-README.md
- README.md
- azure/src/main/java/sunstone/azure/impl/AzureArmTemplateCloudDeploymentManager.java
- azure/src/main/java/sunstone/azure/impl/AzureConfig.java
- azure/src/main/java/sunstone/azure/impl/AzureUtils.java
automatically download all possible logs from azure on deployment failure.
resolves #198
> log download on failure

- aws/src/main/java/sunstone/aws/impl/AwsCloudFormationCloudDeploymentManager.java
- aws/src/main/java/sunstone/aws/impl/AwsUtils.java
> download AWS logs on deployment failure
